version: 0.2

phases:
  install:
    commands:
      # this is here for debug purposes
      - printenv

  pre_build:
    commands:
      - dotnet restore ExampleProject.sln
  build:
    commands:
      - dotnet build ExampleProject.sln -c Release

      - dotnet test ./LambdaFunction/test/LambdaFunction.UnitTests -c Release --no-build
      - mv ./LambdaFunction/test/LambdaFunction.UnitTests/bin/Release/netcoreapp2.1/BDDfy.html ./LambdaFunction-Unit-Tests.html

      - dotnet publish ./LambdaFunction/src/LambdaFunction/ --no-build -c Release -o ../../../publish/lambda

      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - lambda_file_name=Lambda.zip

      - file_name=ExampleProject-$CODEBUILD_RESOLVED_SOURCE_VERSION.zip
      - if [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/master" ] ; then file_name=ExampleProject.zip ; fi
      - if [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "" ] ; then file_name=ExampleProject.zip ; fi
      - echo $file_name

artifacts:
  type: zip
  files:
    - ExampleProject.template
    - LambdaFunction-Unit-Tests.html
  name: $file_name
  secondary-artifacts:
    LambdaFunction:
      base-directory: 'publish/lambda'
      files:
        - '**/*'
      name: $lambda_file_name
