AWSTemplateFormatVersion: '2010-09-09'
Description: Cross account deploy stack.
Parameters:
  BuildAccount:
    Description: AWS AccountNumber for the Build Account
    Type: Number
  BuildAccountKMSKeyArn:
    Description: The ARN of the KMS key used in the pipeline S3 bucket(s)
    Type: String
  PipelineBucket:
    Description: The bucket used for the pipelines.
    Type: String
  SecondaryPipelineBucket:
    Description: The secondary region's Pipeline bucket. This value is required if you are using a secondary region.
    Type: String
  SecondaryCrossAccountCMK:
    Description: The secondary region's Cross Account CMK. This value is required if you are using a secondary region.
    Type: String
Conditions:
  HasSecondaryRegion:
    Fn::Not:
      - Fn::Equals:
          - ''
          - !Ref SecondaryPipelineBucket
Resources:
  CrossAccountCodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: CrossAccount-CodePipeline
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              AWS: !Ref BuildAccount
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service: codepipeline.amazonaws.com
      ManagedPolicyArns:
        - !Ref CrossAccountCodePipelinePolicy
  CrossAccountCodePipelinePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: CrossAccount-CodePipeline
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'codepipeline:*'
              - 'iam:ListRoles'
              - 'cloudformation:Describe*'
              - 'cloudFormation:List*'
              - 'codebuild:BatchGetBuilds'
              - 'codebuild:StartBuild'
              - 'cloudformation:CreateStack'
              - 'cloudformation:DeleteStack'
              - 'cloudformation:DescribeStacks'
              - 'cloudformation:UpdateStack'
              - 'cloudformation:CreateChangeSet'
              - 'cloudformation:DeleteChangeSet'
              - 'cloudformation:DescribeChangeSet'
              - 'cloudformation:ExecuteChangeSet'
              - 'cloudformation:SetStackPolicy'
              - 'cloudformation:ValidateTemplate'
              - 's3:ListAllMyBuckets'
              - 's3:GetBucketLocation'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:GenerateDataKey*'
            Resource:
              - !Ref BuildAccountKMSKeyArn
              - Fn::If:
                  - HasSecondaryRegion
                  - !Ref SecondaryCrossAccountCMK
                  - !Ref AWS::NoValue
          - Action:
              - 's3:GetBucketPolicy'
              - 's3:ListBucket'
              - 's3:GetObject'
              - 's3:PutObject'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${PipelineBucket}'
              - !Sub 'arn:aws:s3:::${PipelineBucket}/*'
              - Fn::If:
                  - HasSecondaryRegion
                  - !Sub arn:aws:s3:::${SecondaryPipelineBucket}
                  - !Ref AWS::NoValue
              - Fn::If:
                  - HasSecondaryRegion
                  - !Sub 'arn:aws:s3:::${SecondaryPipelineBucket}/*'
                  - !Ref AWS::NoValue
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:role/CrossAccount-CodePipeline
              - !Sub arn:aws:iam::${AWS::AccountId}:role/CrossAccount-CloudFormation
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:role/CrossAccount-CloudFormation

  CrossAccountCloudFormationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: CrossAccount-CloudFormation
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
      ManagedPolicyArns:
        - !Ref CrossAccountCloudFormationPolicy
        - 'arn:aws:iam::aws:policy/AdministratorAccess' # this isn't the policy we want here - we really need to clean up the CrossAccount-CloudFormationPolicy and make it do what we need it to do
  CrossAccountCloudFormationPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      #Description: Policy for Cross Account CloudFormation
      ManagedPolicyName: CrossAccount-CloudFormation
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - 'dynamodb:CreateTable'
              - 'dynamodb:DeleteTable'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:UpdateTable'
            Effect: Allow
            Resource:
              - '*'
          - Action:
              - 'route53:ChangeResourceRecordSets'
              - 'route53:ListResourceRecordSets'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'route53:GetChange'
              - 'route53:GetHostedZone'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'lambda:AddPermission'
              - 'lambda:CreateFunction'
              - 'lambda:DeleteFunction'
              - 'lambda:GetFunction'
              - 'lambda:GetFunctionConfiguration'
              - 'lambda:ListTags'
              - 'lambda:RemovePermission'
              - 'lambda:TagResource'
              - 'lambda:UntagResource'
              - 'lambda:UpdateFunction'
              - 'lambda:UpdateFunctionCode'
              - 'lambda:UpdateFunctionConfiguration'
            Effect: Allow
            Resource:
              - '*'
          - Action:
              - 'logs:CreateLogGroup'
              - 'logs:DeleteLogGroup'
              - 'logs:DeleteMetricFilter'
              - 'logs:DeleteRetentionPolicy'
              - 'logs:DeleteSubscriptionFilter'
              - 'logs:DescribeLogGroups'
              - 'logs:DescribeMetricFilters'
              - 'logs:DescribeSubscriptionFilters'
              - 'logs:FilterLogEvents'
              - 'logs:ListTagsLogGroup'
              - 'logs:PutMetricFilter'
              - 'logs:PutRetentionPolicy'
              - 'logs:PutSubscriptionFilter'
              - 'logs:TagLogGroup'
              - 'logs:UntagLogGroup'
            Effect: Allow
            Resource:
              - '*'
          - Action:
              - 'events:DeleteRule'
              - 'events:DescribeRule'
              - 'events:DisableRule'
              - 'events:EnableRule'
              - 'events:PutRule'
              - 'events:RemoveTargets'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'cloudwatch:*Alarms*'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'iam:AttachRolePolicy'
              - 'iam:CreateRole'
              - 'iam:CreateServiceLinkedRole'
              - 'iam:DeleteRole'
              - 'iam:DeleteServiceLinkedRole'
              - 'iam:DetachRolePolicy'
              - 'iam:GetRole'
              - 'iam:ListAttachedRolePolicies'
              - 'iam:ListPolicyVersions'
              - 'iam:ListRoleTags'
              - 'iam:TagRole'
              - 'iam:UntagRole'
              - 'iam:UpdateRole'
              - 'iam:UpdateRoleDescription'
            Effect: Allow
            Resource:
              - '*'
          - Action:
              - 'iam:CreatePolicy'
              - 'iam:DeletePolicy'
              - 'iam:GetPolicy'
              - 'iam:ListEntitiesForPolicy'
            Effect: Allow
            Resource:
              - '*'
          - Action: 'cloudformation:*'
            Effect: Allow
            Resource: '*'
Outputs:
  CrossAccountCloudFormationRoleArn:
    Description: The ARN for the cloud formation role.
    Value: !GetAtt CrossAccountCloudFormationRole.Arn
  CrossAccountCodePipelineRoleArn:
    Description: The code pipeline cloud formation role.
    Value: !GetAtt CrossAccountCodePipelineRole.Arn
