AWSTemplateFormatVersion: '2010-09-09'
Description: Cross account regional stack.
Parameters:
  DeploymentOrgPath:
    Type: String
Resources:
  KMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: Used by Assumed Roles in Dev/Test/Prod accounts to Encrypt/Decrypt code
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Ref 'AWS::StackName'
        Statement:
          - Sid: Allows admin of the key
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
          - Effect: Allow
            Principal: '*'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
            Condition:
              ArnLike:
                aws:PrincipalArn: arn:aws:iam::*:role/CrossAccountCodePipeline
              ForAnyValue:StringLike:
                aws:PrincipalOrgPaths:
                  - !Ref DeploymentOrgPath
          - Effect: Allow
            Principal: !Sub 'arn:aws:iam::${AWS::AccountId}:role/CrossAccountPipelineSyncArtifacts'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
  KMSAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: alias/codepipeline-crossaccounts
      TargetKeyId: !Ref KMSKey
  ArtifactBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !GetAtt KMSKey.Arn
              SSEAlgorithm: 'aws:kms'
  ArtifactBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:*'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${ArtifactBucket}'
              - !Sub 'arn:aws:s3:::${ArtifactBucket}/*'
            Principal: '*'
            Condition:
              ArnLike:
                aws:PrincipalArn: arn:aws:iam::*:role/CrossAccountCloudFormation
              ForAnyValue:StringLike:
                aws:PrincipalOrgPaths:
                  - !Ref DeploymentOrgPath
          - Action:
              - 's3:*'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${ArtifactBucket}'
              - !Sub 'arn:aws:s3:::${ArtifactBucket}/*'
            Principal: '*'
            Condition:
              ArnLike:
                aws:PrincipalArn: arn:aws:iam::*:role/CrossAccountCodePipeline
              ForAnyValue:StringLike:
                aws:PrincipalOrgPaths:
                  - !Ref DeploymentOrgPath
          - Action:
              - 's3:*'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${ArtifactBucket}'
              - !Sub 'arn:aws:s3:::${ArtifactBucket}/*'
            Principal: !Sub 'arn:aws:iam::${AWS::AccountId}:role/CrossAccountPipelineSyncArtifacts'
Outputs:
  CMK:
    Description: The CMK that is used for cross account access
    Value: !GetAtt KMSKey.Arn
    Export:
      Name: CrossAccountCMK
  PipelineBucket:
    Description: The bucket for artifacts
    Value: !Ref ArtifactBucket
    Export:
      Name: PipelineBucket
