AWSTemplateFormatVersion: '2010-09-09'
Description: Cross account developer stack.
Parameters:
  ReplicationFunctionRoleArn:
    Description: The ARN of the replication function role in the main account.
    Type: String
Resources:
  BuildBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !ImportValue BuildBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:*'
            Effect: Allow
            Resource:
              - 'Fn::Sub':
                  - 'arn:aws:s3:::${Bucket}'
                  - Bucket: !ImportValue BuildBucket
              - 'Fn::Sub':
                  - 'arn:aws:s3:::${Bucket}/*'
                  - Bucket: !ImportValue BuildBucket
            Principal:
              AWS: !Ref ReplicationFunctionRoleArn
