AWSTemplateFormatVersion: '2010-09-09'
Description: Example Project Core
Resources:
  Table:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ExampleProject
      AttributeDefinitions:
        - AttributeName: Partition
          AttributeType: S
        - AttributeName: Sort
          AttributeType: S
        - AttributeName: Gsi1Partition
          AttributeType: S
        - AttributeName: Gsi1Sort
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: GSI_1
          KeySchema:
            - AttributeName: Gsi1Partition
              KeyType: HASH
            - AttributeName: Gsi1Sort
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: Partition
          KeyType: HASH
        - AttributeName: Sort
          KeyType: RANGE
